libros/urls.py
from django.contrib import admin
from django.urls import path
from .views import addBook

app_name = "libros"
urlpatterns = [
    path('nuevolibro', addBook, name="addBook"),
] 

tiendaHarryPotter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import logout
from libros.views import index, carrito
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('logout/', logout, name="logout"),
    path('', index, name="index"),
    path('libro/', include('libros.urls')),
    path('carrito/', carrito, name="carrito"),
    path('venta/', include('ventas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from .views import register, loginin

app_name = "users"
urlpatterns = [
    path('register', register, name="register"),
    path('login', loginin, name="login"),
] 

ventas/urls.py
from django.urls import path
from .views import venta, reportes

app_name = "ventas"
urlpatterns = [
    path('nuevolibro', venta, name="venta"),
    path('reportes', reportes, name="reportes"),
] 

libros/models.py
from django.db import models

# Create your models here.
class libro(models.Model):
  titulo = models.CharField(max_length=100)
  precio = models.FloatField()
  disponibles = models.PositiveIntegerField()
  imagen = models.ImageField(upload_to='images/', blank = True)

  def __str__(self):
    return str(self.titulo)

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TipoUsuario(models.Model):
  user = models.ForeignKey(
    User,
    on_delete=models.CASCADE
  )
  tipo = models.CharField(max_length=50, default="cliente")

  def __str__(self):
    return str(self.user.email) + " - " + str(self.tipo)

ventas/models.py
from django.db import models
from django.contrib.auth.models import User
from libros.models import libro

# Create your models here.
class Venta(models.Model):
  user = models.ForeignKey(
    User,
    on_delete=models.CASCADE
  )
  libro = models.ForeignKey(
    libro,
    on_delete=models.CASCADE
  )
  fecha_hora = models.DateTimeField(auto_now=True) 
  cantidad = models.PositiveIntegerField()
  total = models.FloatField(default=0.0)

  def __str__(self):
    return str(self.user.email) + " -> " + str(self.libro.titulo)

libros/views.py
from django.shortcuts import render
from .models import libro
from django.contrib.auth.decorators import login_required
from users.models import TipoUsuario
from django.shortcuts import redirect, reverse

# Create your views here.
@login_required
def addBook(request):
  usuario = request.user
  #tipo_usuario = TipoUsuario.objects.get(user = usuario)
  if (not usuario.is_staff):
    return redirect(reverse('index'))
  context = {}
  if request.method == "POST":
    upload_file = ""
    try:
      upload_file = request.FILES['imagen']
      # for validate extensio of imagen, firts separate the image name using .
      extension = str(upload_file).split(".")
      # then get only the extension
      extension = extension[len(extension) - 1]
      if (extension != "png" and extension != "jpg" and extension != "jpeg"):
        context['imagen_error'] = "La imagen debe ser extension .png, .jpg o jpeg"
    except:
      pass
      
    if int(request.POST.get('precio')) < 0:
      context['precio_error'] = "El precio no puede ser menor a 0"
    elif int(request.POST.get('disponible')) < 0:
      context['disponible_error'] = "La cantidad de libros disponibles no pueden ser menor a 0"
    else:
      book = libro(
        titulo = request.POST.get('titulo'),
        precio = request.POST.get('precio'),
        disponibles = request.POST.get('disponible'),
        imagen = upload_file
      )
      book.save()
      context['sucessfull'] = "Libro añadido con éxito"

  return render(request, 'admin/libro.html', context)

@login_required
def index(request):
  context = {}
  libros = libro.objects.all()
  context['libros'] = libros  
  return render(request, 'index.html', context)

@login_required
def carrito(request):
  context = {}
  libros = []
  if request.method == "GET":
    context['cancelacion'] = "Su compra se ha cancelado"
    return render(request, 'carrito.html', context)

  if request.method == "POST":
    lista_carrito = request.POST.dict()
    # remove the csrf_token of list
    del lista_carrito['csrfmiddlewaretoken'] 
    lista_carrito = list(lista_carrito)
    print(lista_carrito)
    valor_compra = 0.0
    for item in lista_carrito:
      cantidad = request.POST.get(item)
      try:
        cantidad = int(request.POST.get(item))
      except:
        pass
      if (cantidad > 0):
        book = libro.objects.get(id = int(item))
        total = cantidad * book.precio
        valor_compra += total
        libros.append([book, cantidad, total])
    context['libros'] = libros
    context['valor_compra'] = valor_compra
    
  return render(request, 'carrito.html', context)

users/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from .models import TipoUsuario

# Create your views here.
def register(request):
  context = {}
  if request.method == "POST":
    # Checks is email already exist
    if len(User.objects.filter(email = request.POST.get('email'))) > 0:
      context['user_exist'] = "Ya se encuentra registrado el correo " + str(request.POST.get('email')) + ", por favor ingresa otro"
    elif len(request.POST.get('password')) < 6:
      context['password'] = "Contraseña muy corta, se esperan minimo 6 caracteres"
    else:
      # Put the email in all required files
      user = User(
            username = request.POST.get('email'),
            first_name = request.POST.get('email'),
            email = request.POST.get('email')
            )
      user.set_password(request.POST.get('password'))
      user.save()
      tipo_usuario = TipoUsuario(user = user)
      tipo_usuario.save()
      context['sucessfull'] = "Usuario registrado con exito"
  return render(request, 'users/register.html', context)

def loginin(request):
  context = {}
  if request.method == "POST":
    email = request.POST['email']
    password = request.POST['password']
    user = authenticate(request, username=email, password=password)
    if user is not None:
      login(request, user)
      return redirect('/')
    else:
      context['error_login'] = "El usuario o la contraseña no coincide"
  return render(request, 'users/login.html', context)

@login_required
def index(request):
  context = {}
  return render(request, 'index.html', context)

ventas/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from libros.models import libro
from django.shortcuts import redirect, reverse
from .models import Venta
from django.contrib.auth.models import User

# Create your views here.
@login_required
def venta(request):
  context = {}
  usuario= request.user
  if request.method == "POST":
    lista_carrito = request.POST.dict()
    del lista_carrito['csrfmiddlewaretoken'] 
    lista_carrito = list(lista_carrito)
    for item in lista_carrito:
      cantidad_vendida = request.POST.get(item)
      try:
        cantidad_vendida = int(request.POST.get(item))
      except:
        pass
      book = libro.objects.get(id = int(item))
      book.disponibles = book.disponibles - cantidad_vendida
      book.save()
      nueva_venta = Venta(
        user = usuario,
        libro = book,
        cantidad = cantidad_vendida,
        total = int(cantidad_vendida) * book.precio 
      )
      nueva_venta.save()
    context['sucessfull'] = "Hemos recibido su solicitud y será procesada por nuestros agentes. Gracias por su compra"
  return render(request, 'index.html', context)

@login_required
def reportes(request):
  context = {}
  usuarios = User.objects.all()
  lista_ventas = []
  for usuario in usuarios:
    try:
      ventas = Venta.objects.filter(user = usuario)
      if len(ventas)>0:
        lista_ventas.append([usuario, ventas])
    except:
      continue

  context['ventas'] = lista_ventas
  print(lista_ventas[0][1])
  return render(request, 'admin/reportes.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% include 'layouts/navbar.html' %}
    {% block content %}
    {% endblock %}
  </div>
  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</body>
  {% block scripts %}
  {% endblock %}
</html>

templates/carrito.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
  Carrito de compras
{% endblock %}

{% block content %}
  <br>
  <h1>Harry Books - Tienda online</h1>

  <hr>
  <br>
  <h4>Carrito de compras</h4>
  <br>

  {% if cancelacion %}
    <div class="alert alert-danger" role="alert">
      {{ cancelacion }}
    </div>
  {% endif %}

  <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Eliminar</th>
          <th scope="col">Libro</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Valor unitario</th>
          <th scope="col">Valor Total</th>
        </tr>
      </thead>
      <tbody>
        <form action="{% url 'ventas:venta' %}" method="POST" id="form_confirmar">
          {% csrf_token %}
          {% for l in libros %}
            <tr id="{{ l.0.id }}_item">
              <th scope="row"><a class="btn btn-danger delete_carrito" id="{{ l.0.id }}" href="#">Eliminar</a></th>
              <td>{{ l.0.titulo }}</td>
              <td>{{ l.1 }}</td>
              <td>{{ l.0.precio }}</td>
              <td id="{{ l.0.id }}_precio">{{ l.2 }}</td>
              <input type="hidden" name="{{ l.0.id }}" value="{{ l.1 }}" id="libro_{{ l.0.id }}">
            </tr>
          {% endfor %}
        </form>
      </tbody>
    </table>

    <br>
    <div class="row">
      <div class="col-5"></div>
      <div id="valor_compra_text">Valor total de la compra: ${{ valor_compra }}</div>
      <input id="valor_compra" name="valor_compra" type="hidden" value="{{ valor_compra }}">
    </div>
    
    {% if not cancelacion and libros %}
      <a class="btn btn-warning text-light" data-toggle="modal" data-target="#modal_cancelar">Cancelar compra</a>
      <a class="btn btn-primary text-light" data-toggle="modal" data-target="#modal_confirmar1">Confirmar compra</a>
      {% include 'layouts/modal_cancelar.html' %}
      {% include 'layouts/modal_confirmar1.html' %}
      {% include 'layouts/modal_confirmar2.html' %}
    {% endif %}

    <form action="{% url 'carrito' %}" method="GET" id="form_cancelar">
      {% csrf_token %}
    </form>

{% endblock %}
{% block scripts %}
    <script type="text/javascript">
      $(document).ready(function(){
        $('.delete_carrito').click(function(){
          var id = this.id;
          var id_item = id + "_item";
          var id_precio = id + "_precio";
          var row_item = document.getElementById(id_item);
          var valor_descontar = document.getElementById(id_precio).innerText;
          var valor_compra = document.getElementById("valor_compra").getAttribute("value");
          var nuevo_total = parseFloat(valor_compra) - parseFloat(valor_descontar);
          document.getElementById("valor_compra_text").innerText = "Valor total de la compra: $" + nuevo_total;
          document.getElementById("valor_compra").setAttribute("value", nuevo_total);
          $(row_item).remove();
        });
      });
    </script>

    <script type="text/javascript">
      $(document).ready(function(){
        $('#confirmar_cancelacion').click(function(){
          document.getElementById("form_cancelar").submit();
        });
      });
    </script>

    <script type="text/javascript">
      $(document).ready(function(){
        $('#confirmar_compra').click(function(){
          document.getElementById("form_confirmar").submit();
        });
      });
    </script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
  Lista de libros
{% endblock %}

{% block content %}
  <br>
  <h1>Harry Books - Tienda online</h1>

  <hr>
  <br>
  <h4>Libros disponibles</h4>
  <br>
  {% if sucessfull %}
    <div class="alert alert-success" role="alert">
      {{ sucessfull }}
    </div>
    <a href="{% url 'index' %}" class="btn btn-primary text-light">Ver listado de libros</a>
  {% endif %}
  <form action="{% url 'carrito' %}" method="POST" id="form_libros">
    {% csrf_token %}
    {% for l in libros %}
      <div class="row">
          <div class="col-2"></div>
          <div class="col-2">
            <img src="{{ l.imagen.url }}" class="float-left" style="width:150px; height:170px;">
          </div>
          <div class="col-1"></div>
          <div class="col-7">
            
            <div class="row">
              <strong><p>{{ l.titulo }}</p></strong>
            </div>
            
            <div class="row">
              Cantidad disponible: {% if l.disponibles == 0 %} Agotado {% else %} {{ l.disponibles }} {% endif %}
            </div>
            
            <div class="row">
              Precio: ${{ l.precio }}
            </div>
            {% if l.disponibles != 0 %}
              <div class="row">
                Agregar al carrito: <input id="{{ l.id }}_cantidad" type="number" min=0 max="{{ l.disponibles }}" value="0"> <a class="btn btn-primary text-white addcarrito" id="{{ l.id }}">Agregar al carrito</a>
                <input type="hidden" name="{{ l.id }}" value="0" id="libro_{{ l.id }}">
              </div>
            {% endif %}          
          </div>        
      </div>
      <br>
    {% endfor %}
  </form>
{% endblock %}

{% block scripts %}
  <script type="text/javascript">
    $(document).ready(function(){
      $('.addcarrito').click(function(){
        var id = this.id;
        var cantidad_input = id + "_cantidad";
        var cantidad = document.getElementById(cantidad_input).value;
        cantidad = parseInt(cantidad)
        var max = document.getElementById(cantidad_input).getAttribute("max");
        max = parseInt(max);
        if (cantidad > max) {
          alert("Cantidad de libros disponibles excedido");
        } else if(cantidad > 0 && cantidad <= max) {
          document.getElementById("libro_" + id).setAttribute("value", cantidad);
          alert("Agregado al carrito")
        }
      });
    });
  </script>

  <script type="text/javascript">
    $(document).ready(function(){
      $('#carrito_compras').click(function(){
        document.getElementById("form_libros").submit(); 
      });
    });
  </script>
{% endblock %}

templates/layouts/modal_cancelar.html
<div class="modal" tabindex="-1" role="dialog" id="modal_cancelar">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cancelar compra</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>¿Está seguro que desea cancelar la compra?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="confirmar_cancelacion">Confirmar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

templates/layouts/modal_confirmar1.html
<div class="modal" tabindex="-1" role="dialog" id="modal_confirmar1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirmar compra</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>¿Está seguro que desea realizar la compra?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_confirmar2">Confirmar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

templates/layouts/modal_confirmar2.html
<div class="modal" tabindex="-1" role="dialog" id="modal_confirmar2">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirmar compra</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Debe confirmar nuevamente su compra</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="confirmar_compra">Confirmar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

templates/layouts/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'index' %}">Libros</a>
        <a class="nav-item nav-link" href="#" id="carrito_compras">Carrito de compras</a>
        {% if user.is_staff %}
          <a class="nav-item nav-link" href="{% url 'libros:addBook' %}">Agregar libro</a>
          <a class="nav-item nav-link" href="{% url 'ventas:reportes' %}">Reportes</a>
        {% endif %}
        <a class="nav-item nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'users:login' %}">Iniciar sesión</a>
        <a class="nav-item nav-link" href="{% url 'users:register' %}">Registro</a>
      {% endif %}
    </div>
  </div>
</nav>

templates/users/login.html
{% extends "base.html" %}
{% block title %}
  Iniciar sesion
{% endblock %}

{% block content %}
  <br>  
  <h1>Inicia sesión en la tienda de libros de Harry Potter</h1>
  
  {% if error_login %}
  <div class="alert alert-danger" role="alert">
    {{ error_login }}
  </div>
  {% endif %}

  <form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="exampleInputEmail1">Correo electronico</label>
      <input required type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese correo" name="email">
      <small id="emailHelp" class="form-text text-muted">Nunca compartiremos tu correo con alguien mas.</small>
      {% if user_exist %}
        <strong> <p class="text-danger">{{ user_exist }}</p> </strong>
      {% endif %}
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Contraseña</label>
      <input required type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingrese su contraseña" min=6 max=20 name="password">
      {% if password %}
        <strong> <p class="text-danger">{{ password }}</p> </strong>
      {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>

{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% block title %}
  Registro de usuarios
{% endblock %}

{% block content %}
 <br>  
  <h1>Registrate en la tienda de libros de Harry Potter</h1>
  
  {% if sucessfull %}
    <div class="alert alert-success" role="alert">
      {{ sucessfull }}
    </div>
  {% endif %}
  
  <form method="POST" action="{% url 'users:register' %}">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="exampleInputEmail1">Correo electronico</label>
      <input required type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese correo" name="email">
      <small id="emailHelp" class="form-text text-muted">Nunca compartiremos tu correo con alguien mas.</small>
      {% if user_exist %}
        <strong> <p class="text-danger">{{ user_exist }}</p> </strong>
      {% endif %}
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Contraseña</label>
      <input required type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingrese su contraseña" min=6 max=20 name="password">
      {% if password %}
        <strong> <p class="text-danger">{{ password }}</p> </strong>
      {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>
{% endblock %}